config/routes.rb
Decisiv::Application.routes.draw do

  
  match '/welcome' => "home#index",:as => :home
  
  match '/thank_you' => "home#thank_you" ,:as => :thank_you
  get "home/index"
  
  
  resources :customers

  resources :market_basket_records

  resources :part_price_records

 
  resources :basic_files do 
    collection do
       get 'new_market_basket_file'
       get 'new_part_price_file'
       get 'download'
       post 'publish'  
       get 'publish_completed'
       get 'publish_failed'
       get 'publish_in_progress'
       
    end
    member do
      get 'validation_error' 
      get 'republish'
    
    end
  end

  match '/uploads'  => 'basic_files#uploads' ,:as => :upload ,:via => :get  
  
  match '/progress_upload' => 'basic_files#upload_in_progress',:as => :in_progress_upload ,:via => :get
  match '/failed_upload' => 'basic_files#upload_failed',:as => :failed_upload ,:via => :get
  
  match '/download_page' => "basic_files#download_page",:as => "download_page"
  
  match '/downloadable_part_price_file' => "basic_files#downloadable_part_price_file",:as => "downloadable_part_price_file"
  
  match '/downloadable_market_basket_file' => "basic_files#downloadable_market_basket_file",:as => "downloadable_market_basket_file"  
  
  match "/download" => "basic_files#download" ,:as => :download
  
  
  devise_for :users
  
  devise_scope :user do
    get "/" => "devise/sessions#new",:as => :login 
    get "/logout" => "devise/sessions#destroy",:as => :logout

  end
  

  resources :users

 
  
  match '/audits' => 'audits#index' ,:as => :audits
  
  match '/export_to_xls' => 'audits#export_to_xls' ,:as => :export_to_xls,:via => :post
  
  
  mount Resque::Server.new, :at => "/resque"

end

app/models/basic_file.rb
class BasicFile < ActiveRecord::Base
 extend StateMachine::MacroMethods
  state_machine :status, :initial => :na do
    event :in_progress do
      transition [:na,:failed] => :publishing
    end
    
    event :marked_as_failed do
      transition all => :failed
    end
    
    
    event :publish do
      transition :publishing => :published
    end
  end
  
  
  

  ## naming this to asset as using name file can cause problem with Ruby having a File class
  mount_uploader :asset,FileUploader
  #has_many :part_price_records ,:dependent => :destroy
  #has_many :market_basket_records,:dependent => :destroy
  validates_presence_of :name
  #validates_uniqueness_of :name
  validates_presence_of :asset,:message => "please attach a file to upload"
  #before_save :clear_any_validation_errors ,:if => :not_a_new_record_or_contain_validation_error
  has_many :validation_errors
  #after_save :start_background_processing
  
  
  scope :published_part_price_file ,where("status=? AND type_of=?","published","PartPrice")
  scope :published_market_basket_file ,where('status=? AND type_of=?',"published","MarketBasket")     
  
  def template_to_render
    "new_".concat(type_of.underscore).concat('_file')
  end
  
  def start_background_processing(user_id)
    case self.type_of
    when "MarketBasket"    
      #MarketBasketDumper.perform(self.id,user_id)
      Resque.enqueue(MarketBasketDumper,self.id,user_id)
    when "PartPrice"
      #PartPriceDumper.perform(self.id,user_id)
      Resque.enqueue(PartPriceDumper,self.id,user_id)
    end
  end
  
  def uploaded?
    self.import_status == "uploaded"
  end
  
  def upload_failed?
    self.import_status == "failed"
  end
  
  def self.publish_file(files)   
    #PublishRecordJob.perform(self.id)
    files.group_by(&:type_of).each do |key,value|
      unless value.empty?
        id = create_a_single_file_instance(key).id
        Resque.enqueue(PublishRecordJob,value.collect(&:id),key,id)
        #PublishRecordJob.perform(value.collect(&:id),key,id)
      end   
    end  
  end
  
 
  def clear_any_validation_errors
    ## Using Sql to avoid single delete of record and long awaiting commit from the above realtional query
    ## Wrapping the code is transaction so that the delete record dont occupy in mysql memory
    ## The below would result a separate query for assoicated record
    #self.validation_errors.delete_all
    ValidationError.where('basic_file_id=?',self.id).delete_all
    #self.transaction do
    #  self.connection.execute("delete from validation_errors where basic_file_id=#{self.id}")
    #end
    #self.validation_errors.destroy_all 
  end
  
 
  private_class_method
  def self.create_a_single_file_instance(typecast)
    ## Create the instance
    SubscriberDownloader.create(:name => "#{typecast.underscore}_#{DateTime.now.to_i}.csv",:file => typecast)
  end
  
  
end

app/controllers/basic_files_controller.rb
class BasicFilesController < ApplicationController
  # GET /basic_files
  # GET /basic_files.json
  include AuditLogger
  authorize_resource
  def index
 
   @basic_files = BasicFile.where('import_status=? AND status =?','uploaded','na')  
    ## @basic_files = BasicFile.group(:type_of)
    respond_to do |format|
      if request.xhr?
        format.html {render :partial => 'upload_done',:layout => false}
      else  
        format.html 
      end
    end
  end

  def uploads
    
  end
  
  def upload_failed
    @basic_files = BasicFile.where('import_status=? AND status =?','failed','na')
    respond_to do |format|
      format.html { render :layout => false }
    end
  end
  
  def upload_in_progress
     @basic_files = BasicFile.where('import_status=? and status= ?','uploading','na')
     respond_to do |format|
        format.html { render :layout => false }
     end
  end
  # GET /basic_files/1
  # GET /basic_files/1.json
  def show
    @basic_file = BasicFile.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @basic_file }
    end
  end

  # GET /basic_files/new
  # GET /basic_files/new.json
  def new_part_price_file
    @basic_file = BasicFile.new
    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
  end


  def new_market_basket_file
    @basic_file = BasicFile.new
    respond_to do |format|
      format.html 
      format.js { render :layout => false }
    end
  end
  
  
  # GET /basic_files/1/edit
  def edit
    @basic_file = BasicFile.find(params[:id])
  end

  # POST /basic_files
  # POST /basic_files.json
  def create 
   # name = params[:basic_file][:name]
    
    @basic_file = BasicFile.find_by_name_and_type_of(params[:basic_file][:name],params[:basic_file][:type_of]) || BasicFile.new(params[:basic_file])
    operation = @basic_file.new_record? ? "create" : "update"
    respond_to do |format|
        if (@basic_file.new_record? ?  @basic_file.save : @basic_file.update_attributes(params[:basic_file].merge('import_status' => 'na',:status => 'na',:published_at => nil)))
          #DeliveryMailer.file_uploaded(@basic_file).deliver
          @basic_file.start_background_processing(current_user.id) 
          audit_log(operation,@basic_file.type_of,"#{current_user.name} created a #{@basic_file.type_of}File")
          format.html { redirect_to @basic_file } 
        else
          format.html { render :action => @basic_file.template_to_render  }
        end
      end
    
    end

  
  
  def validation_error
    @basic_file = BasicFile.find(params[:id])
    @validation_errors = JSON.parse($redis.get("basic_file_#{@basic_file.id}")) rescue [] #@basic_file.validation_errors
    respond_to do |format|
      format.html { render :layout => false }
    end
  end 
  # PUT /basic_files/1
  # PUT /basic_files/1.json
  def update
    @basic_file = BasicFile.find(params[:id])
    respond_to do |format|
      if @basic_file.update_attributes(params[:basic_file].merge('import_status' => 'na',:status => 'na',:published_at => nil))
        #DeliveryMailer.file_uploaded(@basic_file).deliver
        #@basic_file.clear_any_validation_errors
        @basic_file.start_background_processing(current_user.id) 
        audit_log("update",@basic_file.type_of,"#{current_user.name} created a #{@basic_file.type_of}File")
        format.html { redirect_to @basic_file } 
      else
      
        format.html { render :action => 'edit'}
      end  
    end
  end

  # DELETE /basic_files/1
  # DELETE /basic_files/1.json
  def destroy
    @basic_file = BasicFile.find(params[:id])
    #audit_log("delete",@basic_file.type_of,"#{current_user.name} deleted a #{@basic_file.type_of}File") 
    @basic_file.destroy

    respond_to do |format|
      format.html { redirect_to basic_files_url }
      format.json { head :no_content }
    end
  end
  
  
  def publish_completed
    @basic_files = BasicFile.where('status=?','published')
    respond_to do |format|
      if request.xhr?
        format.html { render :partial => "publish",:layout => false }
      else
        format.html
      end
    end
  end
  
  def publish_failed
    @basic_files = BasicFile.where('status=?','failed')
    respond_to do |format|
      format.html { render :partial=> 'publish',:layout => false }
    end  
  end
  
  def publish_in_progress
    @basic_files = BasicFile.where('status =?','publishing')
    respond_to do |format|
      format.html { render :partial=> 'publish',:layout => false }
    end
  end
  
  def publish

    files = BasicFile.where('id in (?)',params[:publish])
   
    respond_to do |format|
        BasicFile.publish_file(files) 
        audit_log("publish",files)
        flash[:message] = "Files are marked for Publishing ..."
        format.html { redirect_to thank_you_path }
     end   
 
  end
  
  def republish
    file = BasicFile.find(params[:id])
  
    respond_to do |format|
      if file.failed?
        audit_log("republish",file.type_of,"#{current_user.name} Republished a #{file.type_of}File") 
        BasicFile.publish_file([file])
        flash[:field_name] = "success"
        flash[:notice] = "#{file.name} is marked for Publishing"  
      else
        flash[:field_name] = "error"
        flash[:error] = "Cannot Republish a file which is not failed"  
      end 
      format.html { redirect_to publish_completed_basic_files_path }
    end
  end
  
  def download_page
    
  end
  
  
  def downloadable_part_price_file
   
    @downloaders = SubscriberDownloader.where('file=? and status=?',"PartPrice","completed").order("id desc")
  end
  
  def downloadable_market_basket_file
    @downloaders = SubscriberDownloader.where('file=? and status=?',"MarketBasket","completed").order("id desc")
  end
  
  #def download_part_price_file
    #audit_log("download","PartPrice","#{current_user.name} downloaded a PartPriceFile")
    #current_user.update_column('part_price_downloaded_at',DateTime.now)
    #redirect_to s3_url('part_price_file.csv')
  #end
  
  #def download_market_basket_file
    #audit_log("download","MarketBasket","#{current_user.name} downloaded a MarketBasketFile")
    #current_user.update_column('market_basket_downloaded_at',DateTime.now)
    #redirect_to s3_url('market_basket_file.csv')
  #end
  
  def download
    file =  SubscriberDownloader.find(params[:id])
    audit_log("download",file.name,"#{current_user.name} downloaded #{file.file}File")
    #$storage.directories.get($BUCKET).files.get(File.join(basicfile.asset.store_dir,basicfile.asset.filename)).body
    send_data(s3_data_for_file(file.name),:filename => file.name)
    #redirect_to s3_url(file.name) 
  end
  
  private 
  def s3_data_for_file(filename)
    $storage.directories.get($BUCKET).files.get("uploads/subscriber/#{filename}").body
  end
  
  def s3_url(filename)
    expires_at = Time.now + (5 * 60)
    $storage.directories.get($BUCKET).files.get_url("uploads/subscriber/#{filename}", expires_at)
  end
end

app/helpers/basic_files_helper.rb
module BasicFilesHelper

  def file_error(file)
   # error = "<span> #{file.error_field} </span> <br/>"
    error = file_content_error(file.validation_errors)
   #error = %q{<ol> <li> Row12 :- Invalid Name</li> </ol> }
   
    return error
  end
  
  def file_content_error(error)
    error_obj = YAML.load(error['error_encountered'])
    "<li> <label class='error_lbl4'>Row_id #{error['row_no']} :- #{error_description(error_obj)} </label> </li>"
  end
  
  def error_description(obj)
    error_field = String.new

    obj.each do |key,value|
      error_field += "#{key} : #{value.join(',')} "
    end
    return error_field
  end
  
  def css_class(css)
    css==controller.action_name ? "active" : ""  
  end
  

end

app/views/basic_files/_form.html.erb
<%= form_for @basic_file ,:multipart => true do |f| %>
  <div class="ovfl-hidden box_exng">
    <div class="wrp_txt" style="margin-bottom:16px">
      <%= f.text_field :name ,:placeholder => "File Name",:class => "text_Basket fl" ,:id => "file_name"%>
    </div> 
    <div>
      <%= f.file_field :asset ,:class => "f1" %>
      <%= f.hidden_field :asset_cache %>
    </div> 
    <label class="link_frgt" >Please upload .csv file</label>
  </div>
  
  <div class="fl" style="width:42px; height:40px; display:block">&nbsp;</div>
  
  <div class="btn_wrp3" style="padding:8px 0 0 0; overflow:hidden">
    <%= f.hidden_field :type_of,:value => type_of  %>
    <div class="d_button fl" >
      <%= link_to 'Back',:back,:style =>"width:65px" %>
    </div>
    <div class="fl" style="width:20px; height:40px; display:block">&nbsp;</div>
    <div class="d_button fr" >
      <%= f.submit "Upload",:style => "width:65px" %>
    </div>
  </div>
<% end %>
<% if @basic_file.new_record? %>
<%= javascript_tag do %>
   $(document).ready(function() {
    $('input[type=file]').bind('change',function() {
     $('#file_name').val($(this).val().split(/(\\|\/)/g).pop());		
   })
  })
<%end%>
<%end%>

app/views/basic_files/_navigation.erb
<div class="left_fnm fl">
  <ul class="left_tab">
    <li class="first">
      <%= link_to 'Upload New File',upload_path %>
      <li class="<%= css_class('index') %>">
        <%= link_to_unless_current("Successful Upload",{:action => :index},{"data-header" => "Successful Upload",:class => "remote_link" ,:remote => true}) %>
        </li>
      <li class="<%= css_class('upload_in_progress') %>">
        <%= link_to_unless_current('Upload in Progress',{:action => 'upload_in_progress'},{:class => "remote_link","data-header" => "Upload in Progress",:remote => true}) %> 
       </li>
      <li class="<%= css_class(name) %>">
        <%= link_to_unless_current('Upload Failure',{:action => 'upload_failed'},{:class => "remote_link failed","data-header" => "Upload Failure",:remote => true}) %> 
      </li>
  </ul>
</div>

app/views/basic_files/_new.html.erb
<%= render :partial => 'form' ,:locals => {:type_of => type_of }%>

app/views/basic_files/_publish.erb
<%= javascript_tag do %>
    function check_checkboxes() {
      if($('input.republished_checkbox').is(':checked')) {
        return true;
      }
      else {
        alert('Please Select atleast one Checkbox'); 
        return false;
      }
    }
<%end%>

<div class="left_fnm fl">
  <ul class="left_tab">
    <li class="first ">
      <%= link_to 'Publish File',basic_files_path %>
    </li>
    <li class="<%= css_class('publish_completed') %>">
       <%= link_to_unless_current("Published File",{:action => :publish_completed},{:class => "remote_link" ,:remote => true,'data-header' => 'Published File'}) %>
    </li>
    <li class="<%= css_class('publish_in_progress') %>">
      <%= link_to_unless_current('Publish in Progress',{:action => :publish_in_progress} ,{:remote => true,:class => "remote_link" ,'data-header' => ' Publish in Progress'}) %>
    </li>
    <li class="last <%= css_class('publish_failed') %>">
      <%= link_to_unless_current('Publish Failure',{:action => :publish_failed},{:remote => true,:class => "remote_link",'data-header' => 'Publish Failure'}) %>
    </li>
  </ul>
</div>
<% if controller.action_name == "publish_failed" %>
  <%= form_tag publish_basic_files_path ,:onsubmit => "return check_checkboxes();" do %>
    <%= render :partial => 'publish_common' %>
  <%end%>
<%else%>
  <%= render :partial => 'publish_common' %>
<%end%>

app/views/basic_files/_publish_common.erb
<div class="rigth_fnm fl ">
  <div class="wrp_1 ovfl-hidden">
    <h3 class="tlt_top">
      <span style="width:122px" class="fl">File Name</span>
      <span style="width:86px" class="fl">File Type</span>
      <span style="width:112px; padding-left:6px; text-align:center" class="fl">Uploaded On</span> 
      <% if controller.action_name == "publish_completed" %>
        <span style="width:85px; padding:0 0 0 11px" class="fl">Published on</span>
       <% elsif controller.action_name == "publish_failed" %>
       <span style="width:85px; padding:0 0 0 11px" class="fl">Select</span>
      <%end%> 
    </h3>
   
    <div class="desc_file_2">   
      <% @basic_files.each do |basic_file| %>
        <div class="wrp_list">
          <ul class="listing_file">
            <li class="frist">
             <a href="<%= basic_file.asset %>" class="link_f"><%= basic_file.name %> </a>
            </li>
            <li class="scnd">
              <% if basic_file.type_of == "PartPrice" %>
                <label>Parts Exchange Price</label>
              <%else%>
                <label>Market Basket Price</label>
              <%end%>
            </li>
            <li class="thrd">
              <label><%= basic_file.uploaded_at.to_date %></label>
            </li>
            <% if controller.action_name == "publish_completed" %>
              <li class="frth">
                <label><%= basic_file.published_at.to_date %></label>
             </li>
            <% elsif controller.action_name == "publish_failed" %>
             <li class="frth">
              <div class="ovfl-hidden">
                <%= check_box_tag 'publish[]',basic_file.id,false,:class => "republished_checkbox",:style => "vertical-align:middle; margin:4px 0 0 0"%>
              </div>
             </li> 
            <%end%> 
          </ul>
        </div>
      <%end%>
    </div>
  </div>
</div>
<% if controller.action_name == "publish_failed" %>
<div class="btn_wrp2 fr" style="padding:15px 5px 0 0">
  <div class="d_button">
    <%= submit_tag "Re-Publish",:style => "width:78px" %>
  </div>
</div>
<%end%>

app/views/basic_files/_upload_done.erb
<%= javascript_tag do %>
    function check_checkboxes() {
      if($('input.published_checkbox').is(':checked')) {
        return true;
      }
      else {
        alert('Please Select atleast one Checkbox'); 
        return false;
      }
    }
<%end%>
<%= render :partial => 'navigation' ,:locals =>{:name  => 'upload_failed'} %>
<%= form_tag publish_basic_files_path ,:onsubmit => "return check_checkboxes();" do %> 
  <%= render 'common' %>
<%end%> 

app/views/basic_files/downloadable_market_basket_file.erb
<%= render :partial => 'common_download' ,:locals => {:file => "Market Basket Exchange Price" }%>

app/views/basic_files/downloadable_part_price_file.erb
<%= render :partial => 'common_download' ,:locals => {:file => "Part Exchange Price" }%>

app/views/basic_files/new_part_price_file.html.erb
<div style="width:388px; margin:0 auto; padding:147px 0px 150px 0;">
  <div class="top1">
    <% if @type_of == "PartPrice" %>
      <h2>Parts Exchange Price File</h2>
    <%else%>
      <h2>Parts Exchange Price File</h2>
    <%end%>  
  </div>
  <div class="bg1">
    <div class="bg2">
      <div class="bg3">
        <% unless @basic_file.errors.empty? %>
          <div class='alert alert-error' >
            <h2>Error Uploading File</h2>
            <%= content_tag(:ol,raw(content_error(:li,@basic_file.errors))) %>
          </div>
        <%end%>
        <div class="wrp_exchange" style="padding:12px 0 0 0">  
            <%= render :partial => "form" ,:locals => {:type_of => "PartPrice"} %>
        </div>
      </div>
    </div>
  </div>
  <div class="end1">
    <div>&nbsp;</div>
  </div>
</div>  

app/views/basic_files/publish_completed.html.erb
<div style="width:737px; margin:0 auto; padding:40px 0 40px 0">
  <div id="<%= flash[:field_name] %>">
    <span><%= flash[:notice] ||= flash[:error]  %></span>
  </div>
  <div class="top1">
    <h2>Published Files</h2>
  </div>
  <div class="bg1_1">
    <div class="bg2_2">
      <div class="bg3_3">
        <div class="ovfl-hidden wrp_wrp_pblsh" id="container" style="padding-bottom:20px">
          <%= render 'publish' %>
        </div>
      </div>
    </div>
  </div>      
  <div class="end1_1">
    <div>&nbsp;</div>
  </div>
</div>

<%= javascript_tag do %>
  $(document).ready(function() {
      var ajaxLoading ;
     $('#container').delegate('a.remote_link','ajax:beforeSend',function(evt, xhr, settings){ 
     		ajaxLoading = new ajaxLoader(document.body, { classOveride: 'blue-loader'} );
     })
     
     $('#container').delegate('a.remote_link','ajax:success',function(evt,data,status,xhr) {
       if (ajaxLoading) { ajaxLoading.remove(); }
       $("#container").html(data);
       var header = $(this).data('header');
       $('div.top1').find('h2').html(header);
     })    
  })
<%end%>

app/views/basic_files/show.html.erb
<% if @basic_file.uploaded? || @basic_file.upload_failed? %>
<div style="width:363px; margin:0 auto; padding:147px 0px 150px 0;">
  <div class="top1">
    <h2 class="rel" >&nbsp;
      <%= link_to raw("&nbsp;"),home_path,:class => "home_link" %>
    </h2>
  </div>
  <div class="bg1_1">
    <div class="bg2_2">
      <div class="bg3_3">
          <div class="upload_wrp"> 
            <!--upload successfully page starts from here-->
              <div class="inn_div">
                <% if @basic_file.uploaded? %>
                  <label class="lbl_u_b">Upload was Successful!</label>
                <%else%>
                    <label class="lbl_u_b">Upload has Failed!</label>
                 <%end%>
                <label class="lbl_u_b" style="font-weight:normal">What would you like to do now?</label>
                <div class="ovfl-hidden upload_sucess">
                  <div class="fl">
                    <div class="d_button" >
                      <% if @basic_file.uploaded? %>
                        <%= link_to "Publish" ,basic_files_path,:style=>"width:100px" %>
                      <%else%>
                         <%= link_to "Inspect" ,basic_files_path(),:style=>"width:100px" %>
                      <%end%>
                    </div>
                  </div>
                  <div class="fr">
                    <div class="d_button" >
                      <%= link_to "Close", home_path,:style => "width:70px" %>
                    </div>
                  </div>
                </div>
              </div>
            <!--end of upload sucessfully .--> 
          </div>
      </div>
    </div>
  </div>
  <div class="end1_1">
    <div>&nbsp;</div>
  </div>
</div> 
<%else%>
  <div style="width:400px; margin:0 auto; padding:147px 0 0 0">
    <div class="top2">
      <h2 class="rel">Upload is in process <%= link_to raw("&nbsp;"),home_path,:class => "home_link" %>
      </h2>
    </div>
    <div class="bg1_1">
      <div class="bg2_2">
        <div class="bg3_3">
          <div style="width:100%; text-align:center">
            <%= image_tag('busy.gif',:alt=> "busy_bybbol") %> 
            <div class="msg_sec">
                <label style="text-align:center; margin:0 0 5px 0; display:block">You will be informed via email on process completion</label>
                <label style="text-align:center; font-weight:bold" class="lbl_u_b">What would you like to do now?</label>
            </div>
            
            <div class="ovfl-hidden upload_sucess" style="padding:0px 0 15px 0; margin:0 auto; width:200px">
              <div class="fl">
                <div class="d_button fl" >
                  <%= link_to 'Upload More',upload_path,:style => "width:125px" %>
                </div>
                <div class="fr">
                  <div class="d_button fl" >
                  <%= link_to "Close" ,home_path ,:style => "width:70px" %>
                  
                </div>
            </div>
          </div>
        </div>
      </div>
     </div> 
    <div class="end1_1">
     <div>&nbsp;</div>
    </div>
  </div>
  <%= javascript_tag do %>
    window.setInterval("window.location.reload();",10000);
  <%end%>   
<%end%>

app/views/basic_files/upload_in_progress.erb
<%= render :partial => 'navigation' ,:locals =>{:name  => 'upload_failed'} %>
<%= render 'common' %>

app/views/basic_files/uploads.html.erb
<div class="admin_sec">
  <div class="text_a">Please select the file type you wish to upload</div>
    <div class="ovfl-hidden btn_sec">
      <div class="fl">
         <% if can? [:new_part_price_file,:new_market_baskey_file],BasicFile %>
           <%= link_to raw(content_tag(:span,"Part Exchange Price File",:style => "width:210px")),new_part_price_file_basic_files_path,:class => "a_button_a" %>
         <%end%>  
      </div>
      <div class="fr">
        <% if can? [:new_part_price_file,:new_market_baskey_file],BasicFile %>
           <%= link_to raw(content_tag(:span,"Market Basket Price File",:style => "width:210px")),new_market_basket_file_basic_files_path,:class => "a_button_a" %>
        <%end%>   
      </div>
    </div>  
  </div>
</div>

app/views/basic_files/validation_error.erb
<%= render :partial => 'navigation' ,:locals =>{:name  => 'validation_error'} %>
<div class="fr wrp_4 ">
  <div class="rigth_fnm2 fr ">
    <h3 class="tlt_top"><span>Error Details</span></h3>
    <div class="ovfl-hidden">
      <div class="details">
        <ul class="error_details">
          <li>
            <label class="fl error_lbl4  ">File Name:</label>
            <label class="fl  frist "><a href="<%= @basic_file.asset %>" class="link_f"><%= @basic_file.name %> </a></label>
          </li>
          <li>
            <label class="fl error_lbl4  ">File Type:</label>
            <label class="fl error_msg_l  ">CSV</label>
          </li>
          <li>
            <label class="fl error_lbl4">Uploaded On:</label>
            <label class="fl error_msg_l"><%= @basic_file.created_at.to_date %></label>
          </li>
          <li>
            <label class="fl error_lb14 ">Statement: </label>
            <label class="fl error_msg_l" style="color:#f10000"><%= @basic_file.error_field %></label>
          </li>
        </ul>
      </div>
    </div>
    <div class="wrp_1 ovfl-hidden">
      <div class="desc_file_2" style="width:441px">
       <% @validation_errors.each do |errr| %>
        <div class="wrp_list" style="height:45px;">
          <ul class="listing_file">
            <%= raw file_content_error(errr) %>         
          </ul>
        </div>
       <%end%>
      </div>
    </div>
  </div>
  <div class="fr" style="padding:10px 0 0 0">
    <div class="d_button fl">
      <%= link_to 'Back',failed_upload_path,:remote => true,:style => "width:78px",:class => "remote_link","data-header" => "Upload Failed" %>
    </div>
  </div>
</div>