config/routes.rb
Decisiv::Application.routes.draw do

  
  match '/welcome' => "home#index",:as => :home
  
  match '/thank_you' => "home#thank_you" ,:as => :thank_you
  get "home/index"
  
  
  resources :customers

  resources :market_basket_records

  resources :part_price_records

 
  resources :basic_files do 
    collection do
       get 'new_market_basket_file'
       get 'new_part_price_file'
       get 'download'
       post 'publish'  
       get 'publish_completed'
       get 'publish_failed'
       get 'publish_in_progress'
       
    end
    member do
      get 'validation_error' 
      get 'republish'
    
    end
  end

  match '/uploads'  => 'basic_files#uploads' ,:as => :upload ,:via => :get  
  
  match '/progress_upload' => 'basic_files#upload_in_progress',:as => :in_progress_upload ,:via => :get
  match '/failed_upload' => 'basic_files#upload_failed',:as => :failed_upload ,:via => :get
  
  match '/download_page' => "basic_files#download_page",:as => "download_page"
  
  match '/downloadable_part_price_file' => "basic_files#downloadable_part_price_file",:as => "downloadable_part_price_file"
  
  match '/downloadable_market_basket_file' => "basic_files#downloadable_market_basket_file",:as => "downloadable_market_basket_file"  
  
  match "/download" => "basic_files#download" ,:as => :download
  
  
  devise_for :users
  
  devise_scope :user do
    get "/" => "devise/sessions#new",:as => :login 
    get "/logout" => "devise/sessions#destroy",:as => :logout

  end
  

  resources :users

 
  
  match '/audits' => 'audits#index' ,:as => :audits
  
  match '/export_to_xls' => 'audits#export_to_xls' ,:as => :export_to_xls,:via => :post
  
  
  mount Resque::Server.new, :at => "/resque"

end

app/models/audit.rb
class Audit < ActiveRecord::Base
 Operation = %w(create update destroy publish republish download)
 
 On = %w(PartPrice MarketBasket)
 default_scope order('logged_time desc')
 self.per_page = 20
 
end

app/controllers/audits_controller.rb
class AuditsController < ApplicationController
  authorize_resource
  
  before_filter :filter_params
  def index
    if @where_clause.empty?
      @audits = Audit.paginate(:page => params[:page])
    else
      @audits = Audit.where(@where_clause.join(" AND "),*@where_value).paginate(:page => params[:page])
    end 
  end  
  
  
  def export_to_xls

    if @where_clause.empty?
      @audits = Audit.select(['audits.operation','audits.performed_on','audits.description','audits.logged_time'])
    else
      @audits = Audit.where(@where_clause.join(" AND "),*@where_value).select(['audits.operation','audits.performed_on','audits.description','audits.logged_time'])
    end 
    send_data(@audits.to_xls,:filename => 'audits.xls')
   
  end
  
  private
  def filter_params
    @where_clause,@where_value = [[],[]]
    if params[:audits].present?
      params[:audits].each do |key,value|
        unless value.empty?
          if key == "start_date" || key == "end_date"
            if key == "start_date"
              @where_clause << "logged_time >= ?"
              @where_value <<  value # DateTime.new(*(params[:audits][:start_date].split("/").collect(&:to_i))).to_s
            elsif key == "end_date"
              @where_clause << "logged_time <= ?" 
              @where_value << value #DateTime.new(*(params[:audits][:end_date].split("/").collect(&:to_i))).to_s
            end
          else
            @where_clause << "#{key}=?"
            @where_value << value
          end 
        end
      end
    end
  end
end

app/helpers/audits_helper.rb
module AuditsHelper
end

app/views/audits/index.html.erb
<%= javascript_tag do %>
  $(document).ready(function() {
     $('#audit_operation').bind('change',function() {
       $('#operation').val($(this).val());
     })
     
     $('#audit_on').bind('change',function() {
       $('#performed_on').val($(this).val());
     })
     
     $('#audit_user_id').bind('change',function() {
       $('#user_id').val($(this).val());
     })
    
     
     
      $('.btn-success').bind('click',function() {
          $('.submit_xls').click();  
          return false;  
      })
      
      $( "#audit_start_date" ).datetimepicker({
        showOn : "button",
        showSecond: true,
        dateFormat: 'yy/mm/dd',
        timeFormat: 'hh:mm:ss', 
        buttonImage : "<%= image_path('calendar.gif') %>",
        buttonImageOnly : true,
        showAnim : 'fade',
        duration : 'slow',
        onClose : function(dateText, inst) {
          $("#audit_end_date").datetimepicker('option','minDate',new Date(dateText));
          $("#start_date").val(dateText);
        }
      });
      
      $( "#audit_end_date" ).datetimepicker({
        showOn : "button",
        showSecond: true,
        dateFormat : 'yy/mm/dd',
        timeFormat: 'hh:mm:ss', 
        buttonImage : "<%= image_path('calendar.gif') %>",
        buttonImageOnly : true,
        showAnim : 'fade',
        duration : 'slow',
        onClose : function(dateText, inst) {
          $("#audit_start_date").datetimepicker('option','maxDate',new Date(dateText));   
          $("#end_date").val(dateText);
        }
      
      });
      
     
  })
  
   function check_input() {
    if ($("#audit_end_date").val() != "" && $("#audit_start_date").val() == "") {
      alert("Please Provide Start Date");
      return false;
    }   
  }
<%end%>

<br/>
<%= form_tag audits_path ,:method => :get ,:onSubmit => "return check_input();",:class => "my_form" do  %>
 <div class="top_form_sec ">
  <div class="top_divider fl">
    <div class="styled-select">
      <%= select_tag 'audits[operation]',options_for_select(Audit::Operation,:selected => params[:audits].present? ? params[:audits]['operation'] : nil),:prompt => 'OPERATION' , :id => 'audit_operation' ,:style => "width:120px" %>
    </div>
  </div>
  <div class="top_divider fl">
    <div class="styled-select">
      <%= select_tag 'audits[performed_on]',options_for_select(Audit::On,:selected => params[:audits].present? ? params[:audits]['performed_on'] : nil ),:prompt => 'PERFORMED ON' ,:id => 'audit_on',:style => "width:150px"  %>
    </div>
  </div>
  <div class="top_divider fl">
    <div class="styled-select">
      <%= select_tag 'audits[user_id]',options_from_collection_for_select(User.all,'id','name',:selected => params[:audits].present? ? params[:audits]['user_id'] : nil),:prompt => 'USER' ,:id => 'audit_user_id',:style => "width:150px" %>
    </div>
  </div>
   <div class="top_divider fl">
    <div class="styled-select">
      <input type="text" name='audits[start_date]' id="audit_start_date" class="text_input f1" style="height:23px;width:120px" value="<%= params[:audits].present? ? params[:audits]['start_date'] : nil %>"></input>&nbsp;
    </div>
  </div>
  &nbsp;&nbsp;&nbsp;&nbsp;
   <div class="top_divider fl">
    <div class="styled-select">
      <input type="text" name='audits[end_date]' id="audit_end_date" style="height:23px;width:120px" value="<%= params[:audits].present? ? params[:audits]['end_date'] : nil %>"> </input>
    </div>
  </div>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <div class="top_divider fl">
    <div class="input_filter">
       <%= submit_tag 'Filter' ,:class => 'flter_btn' %>
    </div>
  </div>
  </div>
<%end%>

<%= form_tag export_to_xls_path ,:method => :post,:class => 'xls_form' ,:onclick => "return check_input();" do %>
  <%= hidden_field_tag 'audits[operation]',params[:audits].present? ? params[:audits]['operation'] : nil,:id =>'operation' %>
  <%= hidden_field_tag 'audits[performed_on]',params[:audits].present? ? params[:audits]['performed_on'] : nil,:id => 'performed_on' %>
  <%= hidden_field_tag 'audits[user_id]',params[:audits].present? ? params[:audits]['user_id'] : nil,:id => 'user_id' %>
 <%= hidden_field_tag 'audits[start_date]',params[:audits].present? ? params[:audits]['start_date'] : nil,:id => 'start_date' %>
  <%= hidden_field_tag 'audits[end_date]',params[:audits].present? ? params[:audits]['end_date'] : nil,:id => 'end_date' %>
  <div class="right_btn">
    <div class="input_filter fr">
      <%= submit_tag 'Export Report',:class => 'submit_xls flter_btn',:style => 'width:107px' %>   
    </div>
  </div>
<%end%>

<div class="ovfl-hidden tbl_sec ">
  <table border="0" cellpadding="0" cellspacing="0" class="tbl_rpt_sec">
    <col width="206"/>
    <col width="250"/>
    <col width="532"/>
    <col width="338"/>
    <tr>
      <th style="padding:0 0 0 5px"> Operation </th>
      <th> Performed on </th>
      <th> Description </th>
      <th> Logged Time </th>
   </tr>
   <% @audits.each do |audit| %>
     <tr class="active">
        <td><%= audit.operation %></td>
        <td><%= audit.performed_on %></td>
        <td><%= audit.description %></td>
        <td><%= audit.logged_time %></td>
    </tr>
   <%end%>
  </table>
</div>
<%= will_paginate @audits %>