config/routes.rb
Decisiv::Application.routes.draw do

  
  match '/welcome' => "home#index",:as => :home
  
  match '/thank_you' => "home#thank_you" ,:as => :thank_you
  get "home/index"
  
  
  resources :customers

  resources :market_basket_records

  resources :part_price_records

 
  resources :basic_files do 
    collection do
       get 'new_market_basket_file'
       get 'new_part_price_file'
       get 'download'
       post 'publish'  
       get 'publish_completed'
       get 'publish_failed'
       get 'publish_in_progress'
       
    end
    member do
      get 'validation_error' 
      get 'republish'
    
    end
  end

  match '/uploads'  => 'basic_files#uploads' ,:as => :upload ,:via => :get  
  
  match '/progress_upload' => 'basic_files#upload_in_progress',:as => :in_progress_upload ,:via => :get
  match '/failed_upload' => 'basic_files#upload_failed',:as => :failed_upload ,:via => :get
  
  match '/download_page' => "basic_files#download_page",:as => "download_page"
  
  match '/downloadable_part_price_file' => "basic_files#downloadable_part_price_file",:as => "downloadable_part_price_file"
  
  match '/downloadable_market_basket_file' => "basic_files#downloadable_market_basket_file",:as => "downloadable_market_basket_file"  
  
  match "/download" => "basic_files#download" ,:as => :download
  
  
  devise_for :users
  
  devise_scope :user do
    get "/" => "devise/sessions#new",:as => :login 
    get "/logout" => "devise/sessions#destroy",:as => :logout

  end
  

  resources :users

 
  
  match '/audits' => 'audits#index' ,:as => :audits
  
  match '/export_to_xls' => 'audits#export_to_xls' ,:as => :export_to_xls,:via => :post
  
  
  mount Resque::Server.new, :at => "/resque"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
  before_filter :user_time_zone
  check_authorization :unless => :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to home_url, :alert => exception.message
  end
  
 private
  def after_sign_in_path_for(resource)
    home_path
  end

  def after_sign_out_path_for(resource)
    login_path
  end
  
  def user_time_zone
    if request.cookies["utc_offset"].present?
     session[:time_zone_offset] ||= -(request.cookies["utc_offset"].to_i * 60)
     Time.zone = ActiveSupport::TimeZone[session[:time_zone_offset]]
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def content_error(tag,arry)
    wrapper = String.new
    if arry.is_a?(ActiveModel::Errors)
      arry.each do |error,description|
        error = :file if error == :asset 
        wrapper += content_tag(tag,"#{error}:#{description}")
      end
    end
    return wrapper 
  end
  
  def active_class(css_class)
    
    if controller.controller_name == css_class ||  css_class == "#{controller.controller_name}##{controller.action_name}" || css_class == inner_classes
       return "active"
    else
      return ""
    end   
  end
  
  
  def inner_classes
    pages = {
      "basic_files#new_part_price_file" => "basic_files#index",
      "basic_files#new_market_basket_file" => "basic_files#index",
      "basic_files#create" => "basic_files#index",
      "basic_files#edit"   => "basic_files#index",
      "basic_files#show"   => "basic_files#index",
      "basic_files#uploads"  => "basic_files#index",
      "basic_files#downloadable_part_price_file" => "basic_files#download_page",
      "basic_files#downloadable_market_basket_file" => "basic_files#download_page",
      "basic_files#download_part_price_file" => "basic_files#download_page",
      "basic_files#download_market_basket_file" => "basic_files#download_page",
    }   
    pages["#{controller.controller_name}##{controller.action_name}"]
  end

end

css_class = "basic_files#upload"

app/views/application/_header.erb
<header id="header">
  <h1 id="logo" class="fl"><a href="/">&nbsp;</a></h1>
  <div class="fr right_top"> 
    <a href="<%= edit_user_path(current_user) %>" class="fl ">Welcome <%= current_user.name %>!</a>
  <%= link_to 'Log Out', logout_path ,:class => "fl link1" %> 
</header>  
<section id="header_bot">
  <div class="fl global_nav"> 
   <%= link_to 'Home',home_path,:class => "f1 #{active_class('home')}" %>
    
   <% if current_user.publisher? %>
    <%= link_to 'User',users_path,:class => "f1 #{active_class('users')}" %> 
    <%= link_to 'Upload',basic_files_path,:class => "f1 #{active_class('basic_files#index')}" %>
    <%= link_to 'Publish',publish_completed_basic_files_path,:class => "f1 #{active_class('basic_files#publish_completed')}" %>
    <%= link_to 'Report',audits_path ,:class => "f1 #{active_class('audits')}" %> 
   <%else%>
     <%= link_to 'User',edit_user_path(current_user),:class => "f1 #{active_class('users')}" %> 
     <%= link_to 'Download',download_page_path,:class => "f1 #{active_class('basic_files#download_page')}" %> 
   <%end%> 
   
  </div>
</section>